#!/usr/bin/env python3
"""Produce full-season raw, analytical, reconciliation, spatial, and gate evidence."""
from __future__ import annotations
import argparse,json,sys,time
from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from integrations.whoscored.controller import validate_cache
from integrations.whoscored.workflows import TEAM_ALIASES,atomic_csv,atomic_json

def main(season:str)->dict:
    started=time.perf_counter();quality=ROOT/f'data/quality/season_{season}';model=ROOT/f'data/models/season_{season}/advanced';manifest=pd.read_csv(ROOT/f'data/reference/whoscored_season_manifest_{season}.csv')
    raw_rows=[]
    for row in manifest.to_dict('records'):
        checked=validate_cache(ROOT/f'data/raw/whoscored/{season}/poc',row);home_ok=away_ok=date_ok=players_ok=False
        if checked['cache_valid']:
            payload=json.loads((ROOT/f"data/raw/whoscored/{season}/poc/match_{int(row['understat_match_id'])}/raw_match.json").read_text(encoding='utf-8'));home_ok=TEAM_ALIASES.get(payload['home'].get('name'))==row['home_club_id'];away_ok=TEAM_ALIASES.get(payload['away'].get('name'))==row['away_club_id'];date_ok=str(payload.get('startDate',''))[:10]==str(row['date']);players_ok=bool(payload.get('playerIdNameDictionary')) and bool(payload['home'].get('players')) and bool(payload['away'].get('players'))
        valid=checked['cache_valid'] and home_ok and away_ok and date_ok and players_ok
        raw_rows.append({**{k:row[k] for k in ['canonical_match_id','understat_match_id','whoscored_match_id','date','home_club_id','away_club_id']},**checked,'home_identity_valid':home_ok,'away_identity_valid':away_ok,'date_valid':date_ok,'player_metadata_valid':players_ok,'classification':'VALID' if valid else ('INVALID' if (ROOT/f"data/raw/whoscored/{season}/poc/match_{int(row['understat_match_id'])}/raw_match.json").exists() else 'MISSING')})
    raw=pd.DataFrame(raw_rows);atomic_csv(raw,quality/f'whoscored_raw_cache_validation_{season}.csv')
    match=pd.read_csv(model/f'whoscored_match_{season}.csv');lineup=pd.read_csv(model/f'whoscored_lineup_{season}.csv');event=pd.read_csv(model/f'whoscored_event_{season}.csv');advanced=pd.read_csv(model/f'advanced_player_match_{season}.csv');team=pd.read_csv(model/f'team_formation_history_{season}.csv');features=pd.read_csv(model/f'team_match_features_{season}.csv');cross=pd.read_csv(ROOT/f'data/reference/whoscored_player_crosswalk_scale_{season}.csv')
    meaningful=set(lineup.loc[lineup.started.eq(True)|lineup.sub_on_minute.notna(),'whoscored_player_id'].astype(int));meaning_cross=cross[cross.whoscored_player_id.isin(meaningful)];unresolved=cross[cross.mapping_status.ne('PROVEN')].copy();unresolved['meaningful_appearance']=unresolved.whoscored_player_id.isin(meaningful);atomic_csv(unresolved,quality/f'whoscored_unresolved_players_{season}.csv')
    transition=team.groupby('club_id',as_index=False).agg(managers_observed=('manager_id','nunique'),matches=('canonical_match_id','nunique'));transition['transition_observed']=transition.managers_observed.gt(1);atomic_csv(transition,quality/f'whoscored_manager_transitions_{season}.csv')
    comparisons=[]
    mappings=[('key_passes','mgr_kp','same event concept'),('successful_dribbles',None,'Fantrax export has no legitimate successful-dribble field'),('aerial_wins','mgr_aer','same outcome concept'),('interceptions','mgr_int','same event concept'),('clearances','mgr_clr','provider definition may differ'),('shots_on_target','mgr_sot','provider definition may differ'),('tackles_vs_tackles_won','mgr_tkw','attempt/event versus won-only definition'),('crosses_vs_accurate_crosses','mgr_ac','attempt versus accurate-only definition')]
    source={'key_passes':'key_passes','successful_dribbles':'dribbles_successful','aerial_wins':'aerials_won','interceptions':'interceptions','clearances':'clearances','shots_on_target':'shots_on_target','tackles_vs_tackles_won':'tackles','crosses_vs_accurate_crosses':'crosses'}
    comparable=advanced[advanced.fantrax_alignment.eq('EXACT_SINGLE_CLUB_MATCH_IN_PERIOD')]
    for metric,fantrax_field,note in mappings:
        if fantrax_field is None:comparisons.append({'metric':metric,'whoscored_field':source[metric],'fantrax_field':pd.NA,'observations':0,'exact_agreement':pd.NA,'near_agreement_abs_le_1':pd.NA,'mean_difference':pd.NA,'median_difference':pd.NA,'classification':'NOT_COMPARABLE_FIELD_UNAVAILABLE','definition_note':note});continue
        part=comparable[[source[metric],fantrax_field]].dropna();diff=part[source[metric]]-part[fantrax_field];comparisons.append({'metric':metric,'whoscored_field':source[metric],'fantrax_field':fantrax_field,'observations':len(part),'exact_agreement':diff.eq(0).mean(),'near_agreement_abs_le_1':diff.abs().le(1).mean(),'mean_difference':diff.mean(),'median_difference':diff.median(),'classification':'COMPARABLE_SAME_CONCEPT' if metric in {'key_passes','aerial_wins','interceptions'} else 'EXPECTED_DEFINITION_MISMATCH','definition_note':note})
    reconciliation=pd.DataFrame(comparisons);atomic_csv(reconciliation,quality/f'whoscored_fantrax_reconciliation_{season}.csv')
    coords=event[['x','y']].stack();ends=event[['end_x','end_y']].stack();passes=event[event.pass_attempted.eq(True)];shots=event[event.is_shot.eq(True)]
    spatial=pd.DataFrame([{'metric':'coordinate_in_range_rate','value':coords.between(0,100).mean()},{'metric':'coordinate_missing_rate','value':event[['x','y']].isna().any(axis=1).mean()},{'metric':'end_coordinate_complete_rate','value':event[['end_x','end_y']].notna().all(axis=1).mean()},{'metric':'shot_average_x','value':shots.x.mean()},{'metric':'pass_average_x_delta','value':(passes.end_x-passes.x).mean()},{'metric':'home_average_event_x','value':event.merge(match[['canonical_match_id','home_club_id']],on='canonical_match_id').loc[lambda x:x.club_id.eq(x.home_club_id),'x'].mean()},{'metric':'away_average_event_x','value':event.merge(match[['canonical_match_id','away_club_id']],on='canonical_match_id').loc[lambda x:x.club_id.eq(x.away_club_id),'x'].mean()}]);atomic_csv(spatial,quality/f'whoscored_spatial_validation_{season}.csv')
    gates=[('raw_cache_completeness',raw.classification.eq('VALID').mean(),1),('match_normalization',len(match)/380,1),('team_mapping',team.club_id.notna().mean(),1),('meaningful_player_mapping',meaning_cross.mapping_status.eq('PROVEN').mean(),.97),('canonical_event_uniqueness',1-event.duplicated(['canonical_match_id','event_id']).mean(),1),('coordinate_validity',coords.between(0,100).mean(),1),('starter_coverage',lineup.groupby('canonical_match_id').started.sum().eq(22).mean(),.95),('starting_role_coverage',lineup.loc[lineup.started.eq(True),'actual_position_standardized'].notna().mean(),.95),('rating_validity',lineup.loc[lineup.rating.notna(),'rating'].between(0,10).mean(),1),('formation_coverage',team.formation.notna().mean(),.95),('manager_coverage',team.manager_id.notna().mean(),.95),('fantrax_exact_attribution_availability',comparable.fantrax_points.notna().mean(),.95)]
    gates=pd.DataFrame([{'gate':n,'observed':v,'threshold':t,'passed':bool(v>=t)} for n,v,t in gates]);atomic_csv(gates,quality/f'whoscored_season_quality_gates_{season}.csv')
    summary={'expected_matches':380,'valid_raw':int(raw.classification.eq('VALID').sum()),'invalid_raw':int(raw.classification.eq('INVALID').sum()),'missing_raw':int(raw.classification.eq('MISSING').sum()),'normalized_matches':len(match),'lineup_rows':len(lineup),'event_rows':len(event),'unique_events':int(event[['canonical_match_id','event_id']].drop_duplicates().shape[0]),'players_observed':int(lineup.whoscored_player_id.nunique()),'players_mapped':int(cross.mapping_status.eq('PROVEN').sum()),'meaningful_players':len(meaningful),'meaningful_mapped':int(meaning_cross.mapping_status.eq('PROVEN').sum()),'meaningful_mapping_rate':float(meaning_cross.mapping_status.eq('PROVEN').mean()),'managers':int(team.manager_id.nunique()),'clubs_with_manager_transitions':int(transition.transition_observed.sum()),'formations_covered':float(team.formation.notna().mean()),'starting_roles_covered':float(lineup.loc[lineup.started.eq(True),'actual_position_standardized'].notna().mean()),'rating_rows':int(lineup.rating.notna().sum()),'understat_exact':int(advanced.understat_alignment.eq('EXACT_PLAYER_MATCH').sum()),'understat_rate':float(advanced.understat_alignment.eq('EXACT_PLAYER_MATCH').mean()),'fantrax_exact_rows':int(comparable.fantrax_points.notna().sum()),'advanced_rows':len(advanced),'team_feature_rows':len(features),'all_gates_passed':bool(gates.passed.all()),'quality_seconds':round(time.perf_counter()-started,3)};atomic_json(summary,quality/f'whoscored_season_validation_summary_{season}.json');print(json.dumps(summary,indent=2));return summary
if __name__=='__main__':p=argparse.ArgumentParser();p.add_argument('--season',default='2526');a=p.parse_args();main(a.season)
